### ISSUE TITLE
Errors running on windows, fixed manually

### ISSUE THREAD

**Issue by LAP87** [masterofobzene/JDproxygenerator#2]
lxml did not want to play ball at the requirement.txt version, so i manually installed the latest and it seems to work.
Then i got urllib3 errors, it did not want to fetch the data from proxy site. so i found this thread and followed the pip install * --upgrade steps.
https://stackoverflow.com/questions/78163280/no-module-named-urllib3-packages-six-moves

Now it works and produces the file as expected!

**Comment by masterofobzene** [comment]
Hey there, late, I know. 

I ran the script with requirements.txt installation and the only "error" that I had is that I have a newer version of urllib3 already installed, but the script worked anyway and generated the output file with the proxies for JD....


Since it seems you managed to make it work on your end, I'm closing this issue.
